version: "3.8"

services:
  apisix-dashboard:
    image: apache/apisix-dashboard:3.0.1-alpine
    container_name: apisix-dashboard
    restart: always
    ports:
      - "9005:9000"
    volumes:
      - ./apisix_config/dashboard/conf.yaml:/usr/local/apisix-dashboard/conf/conf.yaml
    depends_on:
      - etcd
    networks:
      - apisix

  apisix:
    image: apache/apisix:3.9.1-debian
    container_name: apisix
    restart: always
    ports:
      - "9080:9080"
      - "9091:9091"
      - "9443:9443"
    volumes:
      - ./apisix_config/apisix/config.yaml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    networks:
      - apisix

  etcd:
    image:  quay.io/coreos/etcd:v3.5.5
    container_name: apisix-etcd
    restart: always
    ports:
      - "2379:2379"
    environment:
      ETCD_ENABLE_V2: "true"
      ALLOW_NONE_AUTHENTICATION: "yes"
      ETCD_ADVERTISE_CLIENT_URLS: "http://etcd:2379"
      ETCD_LISTEN_CLIENT_URLS: "http://0.0.0.0:2379"
    volumes:
      - etcd_data:/bitnami/etcd
    networks:
      - apisix

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
    driver: local