version: '3.8'

# Common environment variables used by Kong services (bootstrap and CP)
x-kong-config: &kong-env
  KONG_DATABASE: postgres
  # Kết nối đến database kong_db với user kong_user trên postgres chính
  KONG_PG_HOST: postgres
  KONG_PG_DATABASE: kong_db
  KONG_PG_USER: kong_user
  KONG_PG_PASSWORD: kong_secure_password
  KONG_LICENSE_DATA: "${KONG_LICENSE_DATA}"
  KONG_DECLARATIVE_CONFIG: /kong_config/kong.yml
  KONG_PLUGINS: "bundled,oidc"

services:
  kong-bootstrap:
    build:
      context: ./kong_config
      dockerfile: Dockerfile
    container_name: kong-bootstrap
    networks:
      - shared_network
    restart: on-failure
    environment:
      <<: *kong-env
      KONG_PASSWORD: handyshake
    command: >
      /bin/sh -c "
        kong migrations bootstrap &&
        kong migrations up &&
        kong migrations finish
      "

  kong-cp:
    build:
      context: ./kong_config
      dockerfile: Dockerfile
    container_name: kong-cp
    restart: on-failure
    networks:
      - shared_network
    environment:
      <<: *kong-env
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
      KONG_ADMIN_GUI_LISTEN: 0.0.0.0:8002, 0.0.0.0:8445 ssl
      KONG_ADMIN_GUI_URL: http://localhost:8002
      KONG_PASSWORD: handyshake
    depends_on:
      - kong-bootstrap
    ports:
      - "8000:8000"  # Proxy HTTP
      - "8543:8443"  # Proxy HTTPS (đổi port để tránh conflict với Keycloak)
      - "8001:8001"  # Admin API HTTP
      - "8444:8444"  # Admin API HTTPS
      - "8002:8002"  # Kong Manager HTTP
      - "8445:8445"  # Kong Manager HTTPS

networks:
  shared_network:
    name: shared_network
    external: true