version: '3.8'

services:
  # Jaeger All-in-One
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "5775:5775/udp"      # Zipkin compact thrift
      - "6831:6831/udp"      # Jaeger compact thrift
      - "6832:6832/udp"      # Jaeger binary thrift
      - "5778:5778"          # Config / sampling
      - "16686:16686"        # Jaeger UI
      - "14250:14250"        # gRPC
      - "14268:14268"        # HTTP
      - "14269:14269"        # Admin port
      - "4317:4317"          # OTLP gRPC
      - "4318:4318"          # OTLP HTTP
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
    networks:
      - shared_network

networks:
  shared_network:
    name: shared_network
    external: true