spring:
  application:
    name: kong-tutorial

server:
  port: 8090
  servlet:
    context-path: /auth

config:
  swagger:
    url: ${server.port}${server.servlet.context-path}
    name: ${spring.application.name}
    title: Kong OIDC Tutorial API Documentation
